export enum TILE_TYPE_ENUM {
  WALL_LEFT_TOP = 'WALL_LEFT_TOP',
  WALL_LEFT_BOTTOM = 'WALL_LEFT_BOTTOM',
  WALL_COLUMN = 'WALL_COLUMN',
  WALL_ROW = 'WALL_ROW',
  WALL_RIGHT_BOTTOM = 'WALL_RIGHT_BOTTOM',
  WALL_RIGHT_TOP = 'WALL_RIGHT_TOP',
  FLOOR = 'FLOOR',
  CLIFF_LEFT = 'CLIFF_LEFT',
  CLIFF_CENTER = 'CLIFF_CENTER',
  CLIFF_RIGHT = 'CLIFF_RIGHT'
}

export enum EVENT_ENUM {
  NEXT_LEVEL = 'NEXT_LEVEL',
  CTRL_DIRECTION = 'CTRL_DIRECTION'
}

export enum CTRL_DIRECTION_ENUM {
  TOP = 'TOP',
  BOTTOM = 'BOTTOM',
  RIGHT = 'RIGHT',
  LEFT = 'LEFT',
  TURN_LEFT = 'TURN_LEFT',
  TURN_RIGHT = 'TURN_RIGHT'
}